### ISSUE TITLE
onFileOver should emit 'FALSE' on 'drop' event

### ISSUE THREAD

**Issue by kphilippaerts** [jkuri/ngx-uploader#132]
When a file gets dropped in the drop zone, the onFileOver event must trigger a 'false' event so that the drop-zone can be unselected again.

I would suggest this addition:

File: **src/directives/ng-file-drop.ts**
Function: **initEvents()**
Place: **At the end of the event listener for 'drop'**
Code: **this.onFileOver.emit(false);**

It works well for me :-)

**Comment by jkuri** [comment]
Why don't you check the documentation? `[ngClass]="{'file-over': hasBaseDropZoneOver}"` should work.

**Comment by kphilippaerts** [comment]
I implemented it that way. When a file is dragged over the drop zone, the class is indeed added, and when the file is dragged out, the class is removed. So that works fine. But when the file is actually dropped on the target, there is no event calling the `fileOverBase` function anymore, so the `hasBaseDropZoneOver` variable stays `true` and the drop zone stays highlighted.

It's actually the same in your online demo. Once you dropped a file on the drop zone, the background of your drop zone stays highlighted.

**Comment by stevenjob** [comment]
#174
