### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by scurk15** [jkuri/ngx-uploader#140]
Is it possible to get a better documentation  page possibly with some basic and advanced examples?

The documentation on here on Github isn't really good and the demo page (http://ng2-uploader.com/) doesn't have any documentation at all.

**Comment by ganySA** [comment]
The example is actually pretty useless.

**Comment by jkuri** [comment]
i will update documentation as soon i'll have time.. possibly this weekend.

**Comment by bhamde** [comment]
where does the documentation exist now? I can only see github and the demo examples - no API doc at all

**Comment by jkuri** [comment]
API docs are back online at http://docs.ngx-uploader.com. sorry for delay though.
