### ISSUE TITLE
Everything working fine, but this error message: ... what does it mean?

### ISSUE THREAD

**Issue by macliems** [jkuri/ngx-uploader#164]
`error_handler.js:50 EXCEPTION: _this.files.filter is not a function
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:55 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:55
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:56 TypeError: _this.files.filter is not a function
    at ng-file-select.ts:41
    at SafeSubscriber.schedulerFn [as _next] (async.js:103)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:77)
    at XMLHttpRequest.xhr.onreadystatechange (ng2-uploader.ts:103)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:346
schedulerFn @ async.js:91
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:77
NgZone.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
ng-file-select.ts:41 Uncaught TypeError: _this.files.filter is not a function
    at ng-file-select.ts:41
    at SafeSubscriber.schedulerFn [as _next] (async.js:103)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:77)
    at XMLHttpRequest.xhr.onreadystatechange (ng2-uploader.ts:103)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:345)`

**Comment by jkuri** [comment]
hey, I will check on this. seems like an issue with new version.

**Comment by Eikc** [comment]
I also recieve this when i use ngFileSelect directive.. it also happens on the demo page :)..

**Comment by jkuri** [comment]
https://github.com/jkuri/ngx-uploader/commit/2fea156716cf228699943589f4e0b5e4738b16e2

**Comment by Eikc** [comment]
Wondering if the npm package will be updated with the fix? :)

**Comment by jkuri** [comment]
`2.0.3` is published, but if error still persist please tell me how can I reproduce it.

**Comment by webtrix** [comment]
@jkuri you should make a habit of it, each time you change something, you make a new release / tag, otherwise there is no telling on which version your code is atm and that's actually really frustrating

**Comment by jkuri** [comment]
this time was just a minor fix. I'll prepare conventional changelog.

**Comment by webtrix** [comment]
Doesn't really matter, it's a change. I would suggest semantic versioning, like they use with Angular. At NPM you've upgrade to v2.0.3 to push this change, so don't see why this can't be done here as well.

**Comment by jkuri** [comment]
@webtrix https://github.com/jkuri/ngx-uploader/blob/master/CHANGELOG.md. will be updated further :)

**Comment by webtrix** [comment]
Yea I know about that. But at the rate you're updating that won't help anymore I think.

**Comment by Eikc** [comment]
I'm actually still seeing the issue, the filter is undefined.. 
on line:
https://github.com/jkuri/ngx-uploader/commit/2fea156716cf228699943589f4e0b5e4738b16e2#diff-813d2fa7b2feded9136ac5e18c306fbcR42

I will try make an example that can reproduce it. but its actually pretty simple:

This is my template with the directives
`
            <label ngFileDrop [ngClass]="{'my-drop-zone-on-drag': hasBaseDropZoneOver}" [options]="options" (onUpload)="handleUpload($event)"
                class="upload-button my-drop-zone">
                <input class="hidden"  ngFileSelect [options]="options" type="file"/>
                   Upload product images here
            </label
`

this is my apart of my component
`
 hasBaseDropZoneOver: boolean = false;
    options: NgUploaderOptions = {
        url: '/api/upload/image'
    };

    handleUpload(data): void {
        if (data && data.response) {
            let result = JSON.parse(data.response);
            this.imageAdded.next({ name: result.name, fileReference: result.fileReference, altText: "", status: 'Ok' });
        }
    }

    fileOverBase(e: any): void {
        this.hasBaseDropZoneOver = e;
    }

    beforeUpload(uploadingFile): void {
    }
`

**Comment by Eikc** [comment]
Ahh i think i know what the issue is ...

When you use an input type="file"

the line: https://github.com/jkuri/ngx-uploader/blob/2fea156716cf228699943589f4e0b5e4738b16e2/src/directives/ng-file-drop.ts#L99

is going to be set to a FileList object, and when you use the ngFileDrop , its an array with filter option..

so i guess the fix will be to check if this.files is an array and use filter, otherwise check files.items.filter instead if its an fileList..

i will have time tomorrow to make a pull request to fix the issue

**Comment by jkuri** [comment]
@Eikc that would be nice, thank you.

**Comment by Eikc** [comment]
@jkuri i have created the pull request :) #168 

I have tested it and it works, it will also make the demo work as expected when using the file input to upload files with :) 

Happy new year 👍 🎆

**Comment by jkuri** [comment]
thanks a ton @Eikc. really appreciate it, I wrote you minor comment. 
Thanks and same to you 👍
