### ISSUE TITLE
error_handler.js:48 EXCEPTION: _this.files.filter is not a function

### ISSUE THREAD

**Issue by wqcsimple** [jkuri/ngx-uploader#166]
![image](https://cloud.githubusercontent.com/assets/7285280/21517058/be42f240-cd16-11e6-8d46-93243a3069b3.png)

**Comment by wronskiPrzemyslaw** [comment]
Yep, I can confirm the same thing

**Comment by jkuri** [comment]
https://github.com/jkuri/ngx-uploader/commit/2fea156716cf228699943589f4e0b5e4738b16e2. published on npm.

**Comment by wqcsimple** [comment]
![image](https://cloud.githubusercontent.com/assets/7285280/21536472/8012d186-cdbe-11e6-94d5-5c3309f95e5f.png)

The error still exists

![image](https://cloud.githubusercontent.com/assets/7285280/21536489/9c367656-cdbe-11e6-8a0c-821aff942c2d.png)

@jkuri

**Comment by jkuri** [comment]
how can I reproduce an error?

**Comment by wqcsimple** [comment]
@jkuri   https://github.com/wqcsimple/uploader-test 
 please test

**Comment by jkuri** [comment]
cannot run the demo, it stuck on `ng serve`.

**Comment by wqcsimple** [comment]
What's wrong?

**Comment by jkuri** [comment]
not sure. works for you?

**Comment by wqcsimple** [comment]
yes,    http://uploader.wwhis.com/   

product url

**Comment by nsankabathula** [comment]
Having same problem, exception "_this.files.filter is not a function".
Any solution for this problem?

**Comment by Kamshak** [comment]
Yep the error still exists, the problem is that the this.files is not an Array but a [FileList](https://developer.mozilla.org/de/docs/Web/API/FileList). FIleList doesn't have a filter function. You could probably use Array.prototype.filter.call
