### ISSUE TITLE
this.files.filter - error

### ISSUE THREAD

**Issue by rrubio** [jkuri/ngx-uploader#167]
Hi Guys,

There seems to be an error (see below) once the file is finished uploading.

file "directives/ng-file-select" line #42.

`error_handler.js:53 TypeError: _this.files.filter is not a function
    at ng-file-select.ts:42
    at SafeSubscriber.schedulerFn [as _next] (async.js:94)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:74)
    at XMLHttpRequest.xhr.onreadystatechange (ngx-uploader.ts:103)
    at XMLHttpRequest.wrapFn [as _onreadystatechange] (zone.js:698)`

**Comment by BY0X15** [comment]
**For upload a single file**

In file "directives/ng-file-select"
Replace **@HostListener('change') onChange(): void {** on
```
@HostListener('change') onChange(): void {
    this.files = this.el.nativeElement.files;

    if (!this.files) {
      return;
    }

    if (this.options.filterExtensions && this.options.allowedExtensions && this.files && this.files.length) {

      const file = this.files[0];

      if (this.options.allowedExtensions.indexOf(file.type) === -1) {

        this.onUploadRejected.emit({file: file, reason: UploadRejected.EXTENSION_NOT_ALLOWED});
      }
    }

    if (this.files.length) {
      this.uploader.addFilesToQueue(this.files);
    }
  }
```

**Comment by naveedahmed1** [comment]
@kiuka  Is there any permanent fix to this error?

**Comment by rrubio** [comment]
Thank you!

**Comment by alex88** [comment]
@jkuri any chance this goes into a tagged release soon?

**Comment by squarewave24** [comment]
same issue. this errors seems to be coming from the library as im not writing any code with filters just following the simple example 

```
core.es5.js:1020 ERROR TypeError: _this.files.filter is not a function
    at ng-file-select.ts:41
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3647)
    at 
```

**Comment by alex88** [comment]
@squarewave24 be sure to upgrade to the latest version

**Comment by squarewave24** [comment]
@alex88 hi, 

i installed it for the first time right before posting so I don't think it would choose an older version? 

it's weird because .files is not empty on the server (node.js) side. i am able to print it out 

```
 res.json(req.files.map(file => {
    let ext = path.extname(file.originalname);
```

**Comment by alex88** [comment]
@squarewave24 I don't know then, I had this issue with an outdated version

**Comment by squarewave24** [comment]
ok 
btw would you happen to know how to retrieve contents of the json file in node.js ? i followed the example but i don't see it anywhere on the request. should it be on req.body ? because that's empty for me :(

**Comment by alex88** [comment]
@squarewave24 afaik when you upload a file it's not a json, it's using multipart encoding, something like this maybe https://stackoverflow.com/a/27951168/690839 It also depends on your http framework if you're using one.
