### ISSUE TITLE
bug in version > 2.0.22

### ISSUE THREAD

**Issue by oskvortsov-bmt** [jkuri/ngx-uploader#191]
Hi 
I try using ngx-uploader version > 2.0.22 and branches master, and i get error
Stable version 2.0.22

**Comment by umens** [comment]
same here. It may be cause by the merge #190 for the multiple instance support.

**Comment by musicEnfanthen** [comment]
got the same error here (ngx-uploader v2.0.22): 

> No provider for NgUploaderService!

Resolved for now by adding

```
import { NgUploaderServiceProvider } from './../services/ngx-uploader';
...
providers: [
   NgUploaderServiceProvider
],
```
wether locally to the component that uses the uploader or globally back to `/node_modules/ngx-uploader/src/module/ngx-uploader.module.ts`.

**Comment by oskvortsov-bmt** [comment]
I try it, but when i try upload file with use drap and drop i get error
