### ISSUE TITLE
Throw away function

### ISSUE THREAD

**Issue by princemaple** [jkuri/ngx-uploader#209]
Hi @jkuri ,

There is a [function](https://github.com/jkuri/ngx-uploader/blob/master/src/classes/ng-uploader-options.class.ts#L45-L47) gets created and thrown away every time an upload option object is created.
Why is that implemented this way? Not that it's a huge performance impact, just curious.
If it's not an intentional design, I'd like to send a PR to move into an ~instance~ method, is that OK?

Regard,
Po

**Comment by jkuri** [comment]
hi @princemaple. yes, sure, send a PR and I will accept it. thanks.

**Comment by princemaple** [comment]
Totally forgot about this one. Sorry. However, now I look at it again it's really not that big of a deal. There is nothing wrong with using a closure to handle this.
