### ISSUE TITLE
firefox FileList has no filter

### ISSUE THREAD

**Issue by zwerg44** [jkuri/ngx-uploader#210]
/src/directives/ng-file-select.ts
this.files = this.files.filter(f => f.name !== data.originalName);

In firefox this.files has type FileList, it has no method filter.
So all this.files.filter in /src/directives/* will fail with "_this.files.filter is not a function"

Supose to have something like this in this.files = this.el.nativeElement.files; assignment:

    this.files = [];
    if (this.el.nativeElement.files && this.el.nativeElement.files.length) {
      for (let i=0; i<this.el.nativeElement.files.length; i++) {
        this.files.push(this.el.nativeElement.files[i]);
      }
    }

Using:
- ubuntu firefox 51.0.1 (64-bit)
- ng2-uploader 2.0.0
- typescript
- angular 2.4.4

**Comment by rafaelcneves** [comment]
The same on Chrome..

**Comment by zwerg44** [comment]
Seems like I used the wrong version.
This was fixed in ngx-uploader 2.0,4 and current 2.2.0 looks ok.
