### ISSUE TITLE
umd bundles

### ISSUE THREAD

**Issue by patrickracicot** [jkuri/ngx-uploader#212]
Please close issue, mistake from my part

**Comment by jkuri** [comment]
added back in https://github.com/jkuri/ngx-uploader/commit/e1e1285fad9a6dde11025201a938ea67775b0d4f. please let me know if it works for you. thanks.

**Comment by patrickracicot** [comment]
Indeed it is now working when targeting the bundles instead of the index.js  Thx

**Comment by jkuri** [comment]
no problem.
