### ISSUE TITLE
How to run in local computer.

### ISSUE THREAD

**Issue by siva2sachin** [jkuri/ngx-uploader#214]
I have installed the packages using npm install build and I tried using npm run dev to  watch for the files change. Could you please help me how to access the page with localhost(means what is the address)?.. Please let me know if I'm doing wrong. Thanks in advance for your help.

**Comment by jkuri** [comment]
you need to run `npm start`.

**Comment by siva2sachin** [comment]
Thanks for your help. I did that but I'm getting below error,

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

In package.json, I don't see a Start command in scripts sections. Am I missing anything?

**Comment by jkuri** [comment]
sorry, i changed this with another module. unfortunatelly this module does not come with a demo included, but I will prepare one in a near future.

**Comment by siva2sachin** [comment]
Thanks. I will try to implement by myself.
