### ISSUE TITLE
Can't find variable: DragEvent in Safari

### ISSUE THREAD

**Issue by hsbalar** [jkuri/ngx-uploader#234]
Getting ReferenceError: Can't find variable: DragEvent when application run in safari browser

**Comment by BenevidesLecontes** [comment]
i'm getting this as well, but when i'm running tests in PhantomJS.

**Comment by hsbalar** [comment]
@BenevidesLecontes Is there any way to work around ?

**Comment by jkuri** [comment]
this is now solved with the new version.
