### ISSUE TITLE
Sending File as encoded String (i.e. base64) in JSON-Struct in option.data

### ISSUE THREAD

**Issue by TomRt** [jkuri/ngx-uploader#239]
Hi, 

first i want to say that you guys make a great job and i'm thankful to use your ngx-uploader modul.

But unfortunately i wasn't able to made the ngx-fileuploader work for my puposes in my current project.
The server i want to upload the file isn't accepting the encoded form-data-syntax the ngx-uploader is sending. 
The server only accepting the file as an encoded base64-string within a json-struct.

And i don't get the ngx-uploader to send only plain JSON-Struct without the form-syntax.

So i decide for myself to modify the ngx-uploader code  a little bit to get the thing working.
Therefore i added an new option-flag 'plainJson' in ngx-uploader-class , default is false.
And i added another if-condition for 'plainJson' in the  ngx-uploader-service.  

To demonstrate the modifications i've forked the ngx-uploader and modified the advanced example code.
See   https://github.com/TomRt/ngx-uploader.git

It would be great to have that kind of configuration possibility in one of the next releases .

Keep up the good work !

Tom

**Comment by jkuri** [comment]
Hi @TomRt, thank you for your kind words. Wondering why you don't make a Pull Request so I can get this thing merged?

**Comment by TomRt** [comment]
I've made a PR and it was accepted
Thanks @jkuri
