### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input' Angular 4

### ISSUE THREAD

**Issue by Crizstian** [jkuri/ngx-uploader#251]
I am using Angular 4 with CLI, and i am recieving this issue.

`
Can't bind to 'options' since it isn't a known property of 'input'. ("                 type="file"
                             ngFileSelect
                             [ERROR ->][options]="options"
                             (onUpload)="handleUpload($event)"
                  "): ng:///UIModule/CreateChannelModalCmpt.html@64:29 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'input'. ("                 type="file"
                             ngFileSelect
                             [ERROR ->][options]="options"
                             (onUpload)="handleUpload($event)"
`

**Comment by jkuri** [comment]
make sure you have included `NgUploaderModule`.

**Comment by Crizstian** [comment]
Didnt work know i am implenting the new version of the api, so im closing this issue
