### ISSUE TITLE
Webpack Vendor Problem

### ISSUE THREAD

**Issue by fatih91** [jkuri/ngx-uploader#254]
After I add the dependency of ngx-uploader to webpack.config.vendor.js and after I run webpack --config webpack.config.vendor.js on the command line to update the vendor bundle I got this error:

>     ERROR in ./~/ngx-uploader/index.ts
>     Module not found: Error: Can't resolve './src/ngx-uploader/module/ngx-uploader.module' in '/Users/.../node_modules/ngx-uploader'
>      @ ./~/ngx-uploader/index.ts 1:0-62
>      @ dll vendor
>     
>     ERROR in ./~/ngx-uploader/index.ts
>     Module not found: Error: Can't resolve './src/ngx-uploader/classes/ngx-uploader.class' in '/Users/.../node_modules/ngx-uploader'
>      @ ./~/ngx-uploader/index.ts 2:0-62
>      @ dll vendor
>     
>     ERROR in ./~/ngx-uploader/index.ts
>     Module not found: Error: Can't resolve './src/ngx-uploader/directives/ng-file-select.directive' in '/Users/.../node_modules/ngx-uploader'
>      @ ./~/ngx-uploader/index.ts 3:0-71
>      @ dll vendor
>     
>     ERROR in ./~/ngx-uploader/index.ts
>     Module not found: Error: Can't resolve './src/ngx-uploader/directives/ng-file-drop.directive' in '/Users/.../node_modules/ngx-uploader'
>      @ ./~/ngx-uploader/index.ts 4:0-69
>      @ dll vendor

But the directory ngx-uploader and the files  existing in the node modules

**Comment by lgleim** [comment]
Similarly when trying to build with ionic-app-script, it errors with 
```
[10:08:53]  Error: ./~/ngx-uploader/index.ts Module build failed: Error: ENOENT: no such file or directory, open 
            '/home/g/prozeo-mvp/node_modules/ngx-uploader/index.js' at Error (native) @ 
            ./src/app/components/feed-components/post-component.module.ts 15:0-48 @ ./src/app/app.module.ts @ 
            ./src/app/main.ts 
Error: ./~/ngx-uploader/index.ts
Module build failed: Error: ENOENT: no such file or directory, open '/home/g/prozeo-mvp/node_modules/ngx-uploader/index.js'
    at Error (native)
 @ ./src/app/components/feed-components/post-component.module.ts 15:0-48
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (/home/g/prozeo-mvp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/home/g/prozeo-mvp/node_modules/@ionic/app-scripts/dist/webpack.js:119:28)
    at /home/g/prozeo-mvp/node_modules/webpack/lib/Compiler.js:256:15
    at Compiler.emitRecords (/home/g/prozeo-mvp/node_modules/webpack/lib/Compiler.js:351:37)
    at /home/g/prozeo-mvp/node_modules/webpack/lib/Compiler.js:249:12
    at /home/g/prozeo-mvp/node_modules/webpack/lib/Compiler.js:344:11
    at next (/home/g/prozeo-mvp/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/home/g/prozeo-mvp/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/g/prozeo-mvp/node_modules/tapable/lib/Tapable.js:158:13)
```

**Comment by jkuri** [comment]
guys can you check with `3.0.2` please, I missed some files with the publish to `npm`. thanks

**Comment by lgleim** [comment]
`3.0.3` seems to work fine. Thanks!

**Comment by fatih91** [comment]
Yes I confirm Igleim it works fine. Thank you very much!

**Comment by jkuri** [comment]
no problem.
