### ISSUE TITLE
How do you change fieldname in this new version?

### ISSUE THREAD

**Issue by ericmaro** [jkuri/ngx-uploader#258]
The new version is nice, but how can I change a fieldname to something like image, logo instead of just file?

**Comment by ericmaro** [comment]
Anyway I went and update your code and add 
`fieldName?: string;`
to interface UploadInput 

and change the append in uploadfile like this
` form.append( event.fieldName || 'file', uploadFile, uploadFile.name);`

I hope you will include this in your next version

**Comment by jkuri** [comment]
its included now, thanks.
