### ISSUE TITLE
Parameter 'platform_id' implicitly has an 'any' type

### ISSUE THREAD

**Issue by cokkiy** [jkuri/ngx-uploader#265]
node_modules/ngx-uploader/src/ngx-uploader/classes/ngx-uploader.class.ts(160,27): error TS7006: Parameter 'observer' implicitly has an 'any' type.
node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts(16,15): error TS7006: Parameter 'platform_id' implicitly has an 'any' type.
node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-select.directive.ts(16,15): error TS7006: Parameter 'platform_id' implicitly has an 'any' type.

ngx-uploader.class.ts line 160 should modified to  return new Observable<UploadOutput>((observer: Observer<UploadOutput>) => {
ng-file-drop.directive.ts and  ng-file-select.directive.ts should modified to constructor( @Inject(PLATFORM_ID) private platform_id: any,private elementRef: ElementRef)

ngx-uploader.class.ts file should import Observer.
import { Observer } from 'rxjs/Observer';

**Comment by CQPosts** [comment]
I get this:
node_modules/ngx-uploader/src/ngx-uploader/classes/ngx-uploader.class.ts(161,27): error TS7006: Parameter 'observer' implicitly has an 'any' type.
