### ISSUE TITLE
Demo Site is Down

### ISSUE THREAD

**Issue by chrisalexander55** [jkuri/ngx-uploader#271]
Please check site.

**Comment by jkuri** [comment]
thanks for report... working on a fix.

**Comment by chrisalexander55** [comment]
Down again, probably the Nth time. People reading this thread should consider the relative instability of OSS examples when deciding to use a component or library. Personally, I'm moving on to contribute to another OSS project.

**Comment by gioragutt** [comment]
This change is needed. I want to know whether to use the library or not, but not without examples. Please handle this

**Comment by jkuri** [comment]
thanks to @marhi weird/neat hack demo is back online! http://ngx-uploader.com/. sorry guys for inconvienience.
