### ISSUE TITLE
Single file upload instead of queue

### ISSUE THREAD

**Issue by ernerock** [jkuri/ngx-uploader#295]
I need to limit the upload to 1 file, having any new file added replace the current one in the queue or a method to clear the queue before a new file is added, in order to always upload 1 file. Any way of doing this?

**Comment by flacohenao** [comment]
@ernerock  Did you find a solution for this?

**Comment by ernerock** [comment]
@flacohenao the tool wasn't working like the demo, at least for me. Ended up forking and editing to my specific needs. Didn't PR because I ended up changing a lot of things others might need.

**Comment by flacohenao** [comment]
Thanks for the reply @ernerock I just ended up emitting a 'delete' event after the use of the tool.. and that was my workaround

**Comment by vlados** [comment]
@flacohenao can you post your solution?
