### ISSUE TITLE
output file response

### ISSUE THREAD

**Issue by jason111neo** [jkuri/ngx-uploader#297]
Is it possible to return file.response when the output type is not done?

**Comment by jason111neo** [comment]
it just does not go past 'uploading'. Under network tab shows response though

**Comment by jkuri** [comment]
i believe that's a problem with your API.

**Comment by jason111neo** [comment]
was trying to figure out if there is a way to get a xhr.response as the previous 2.x branch could do so with "data.xhr.__zone_symbol__originalInstance"

**Comment by jason111neo** [comment]
it would be good if there is a base64 data like "handlepreview" had

**Comment by jason111neo** [comment]
I have found the issue. "pace/pace.js" is causing the request to be stucked at 'uploading'

**Comment by vivian7169** [comment]
@jason111neo 
I am encountering the same issue, even I set the pace options as below, still can't work (can't get output 'done'... ). May I know how you solved the issue? Thanks.

window.paceOptions = {
    ajax: false, 
    elements: false,
    document: false,
    eventLag: false,
    restartOnPushState: false,
    restartOnRequestAfter: false
};

**Comment by VivekIshir** [comment]
How i can file data in  base64 format? any help will be appreciable. Thanks
