### ISSUE TITLE
Uploader doesnt upload all files in the queue, when files are added one by one

### ISSUE THREAD

**Issue by jvielrco** [jkuri/ngx-uploader#302]
Hi,

When I select multiple files in the file select (or by drag&drop), all files are uploaded successfully.
However, when I add files to the queue one by one, only the last file is uploaded.
I can reproduce on your online example at http://ngx-uploader.com/

Thanks.

**Comment by oleosjo** [comment]
So has this been fixed or not? It's happening to me on 3.3.6
