### ISSUE TITLE
How to preview image before upload?

### ISSUE THREAD

**Issue by lagmanzaza** [jkuri/ngx-uploader#320]

**Comment by lagmanzaza** [comment]
I can fix it

**Comment by TonyLuo** [comment]
@lagmanzaza how to fix it?

**Comment by lagmanzaza** [comment]
readUrl(event) {
    if (event.target.files && event.target.files[0]) {
      var reader = new FileReader();

      reader.onload = (event) => {
        let data: any = event.target;
        this.previewImage = data.result;
      }

      reader.readAsDataURL(event.target.files[0]);
    }
  }
