### ISSUE TITLE
[Blocking Bug] 3.3.10 : Comipilation error 

### ISSUE THREAD

**Issue by AlanCrevon** [jkuri/ngx-uploader#335]
Hi.

3.3.10 rises an error. Same code compiles without any error on 3.3.9.
I replaced manually my path by "XXX" .

```
ERROR in Unexpected value 'NgUploaderModule in /home/gitlab-runner/builds/972e3e89/0/gits/superisco-frontend/node_modules/ngx-uploader/lib/src/ngx-uploader/module/ngx-uploader.module.d.ts' imported by the module 'AvatarManagerModule in XXX/src/app/modules/_shared/modules/avatar-manager/avatar-manager.module.ts'. Please add a @NgModule annotation.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'XXX/src'
resolve './$$_gendir/app/app.module.ngfactory' in 'XXX/src'
  using description file: XXX/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: XXX/package.json (relative path: ./src)
    using description file: XXX/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        XXX/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        XXX/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
       XXX/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        XXX/src/$$_gendir/app/app.module.ngfactory doesn't exist
```

For info, here is my AvatarManagerModule : 

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MaterialModule, MdSelectModule } from '@angular/material';
import { NgUploaderModule } from 'ngx-uploader';
import { AvatarManagerComponent } from './components/avatar-manager/avatar-manager.component';
import { AvatarManagerService } from './services/avatar-manager.service';
import { BlazyDirective } from 'app/modules/_shared/directives/blazy.directive';

@NgModule({
  declarations: [
    AvatarManagerComponent,
    BlazyDirective,
  ],
  imports: [
    CommonModule,
    MaterialModule,
    NgUploaderModule,
  ],
  exports: [
    AvatarManagerComponent,
    NgUploaderModule,
    BlazyDirective,
  ],
  providers: [
    AvatarManagerService,
  ],
  bootstrap: []
})
export class AvatarManagerModule {}
```

Cheers, and thanks for this very usefull library.

**Comment by vincent-cm** [comment]
Almost same here, aot build failed with:

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Unexpected value 'NgUploaderModule in node_modules/ngx-uploader/lib/src/ngx-uploader/module/ngx-uploader.module.d.ts' imported by the module 'CoreModule in /core.module.ts'. Please add a @NgModule annotation.

**Comment by lincolnthree** [comment]
Same here.

**Comment by leo6104** [comment]
@lincolnthree In my project, it works with ionic-app-scripts build. 
I guess, this issue might be something wrong with webpack cli configuration. 
Can you comment your 'webpack.config.js' ?

**Comment by lincolnthree** [comment]
I don't have / haven't made any customizations to this file. Where can I find the one you're looking for?

**Comment by nicksav** [comment]
same here. Have to roll back to 3.0.6

**Comment by jkuri** [comment]
sorry for inconvenience, fixed now.

**Comment by lincolnthree** [comment]
Using 3.3.11

```
[08:33:32]  copy finished in 33.82 s 
[08:33:46]  ionic-app-script task: "build" 
[08:33:46]  Error: ./node_modules/ngx-uploader/src/ngx-uploader/module/ngx-uploader.module.ts Module build failed: 
            TypeError: Cannot read property 'content' of undefined at Object.optimizationLoader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
            @ ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts 39:0-85 @ ./src lazy @ 
            ./node_modules/ionic-angular/util/ng-module-loader.js @ ./src/app/app.module.ngfactory.js @ 
            ./src/app/main.ts,./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-select.directive.ts Module 
            build failed: TypeError: Cannot read property 'content' of undefined at Object.optimizationLoader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
            @ ./src/pages/manage-event-pairings/manage-event-pairings.ngfactory.js 47:0-94 @ 
            ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts @ ./src lazy @ 
            ./node_modules/ionic-angular/util/ng-module-loader.js @ ./src/app/app.module.ngfactory.js @ 
            ./src/app/main.ts,./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts Module 
            build failed: TypeError: Cannot read property 'content' of undefined at Object.optimizationLoader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
            at Object.loader 
            (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
            @ ./src/pages/manage-event-pairings/manage-event-pairings.ngfactory.js 31:0-92 @ 
            ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts @ ./src lazy @ 
            ./node_modules/ionic-angular/util/ng-module-loader.js @ ./src/app/app.module.ngfactory.js @ 
            ./src/app/main.ts 
Error: ./node_modules/ngx-uploader/src/ngx-uploader/module/ngx-uploader.module.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts 39:0-85
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-select.directive.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/manage-event-pairings/manage-event-pairings.ngfactory.js 47:0-94
 @ ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/manage-event-pairings/manage-event-pairings.ngfactory.js 31:0-92
 @ ./src/pages/manage-event-pairings/manage-event-pairings.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by leo6104** [comment]
@lincolnthree Can you try this? 
1. `npm install ngx-uploader@3.3.10 `
2. copy 'node_modules/ngx-uploader/src/' to 'node_modules/ngx-uploader/lib/src' 
3. ng build  or ionic build 

To resolve #305 and this issue (#335),  
1. set declaration: true in tsconfig.bundle.json
2. include .ts file (ngx-uploader/**/*.ts) in lib folder. 
-> 3.3.10 version doesn't include ts file in lib folder.

**Comment by Demi-ob** [comment]
Cannot find .map files after applying this fix

**Comment by Demi-ob** [comment]
Error: ./node_modules/ngx-uploader/lib/src/ngx-uploader/classes/ngx-uploader.class.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desk
top\Projects\hubble\node_modules\ngx-uploader\lib\src\ngx-uploader\classes\ngx-uploader.cla
ss.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 2:0-62
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/directives/ng-file-dr
op.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desk
top\Projects\hubble\node_modules\ngx-uploader\lib\src\ngx-uploader\directives\ng-file-drop.
directive.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 4:0-69
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/directives/ng-file-se
lect.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desk
top\Projects\hubble\node_modules\ngx-uploader\lib\src\ngx-uploader\directives\ng-file-selec
t.directive.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 3:0-71
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/module/ngx-uploader.module.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desktop\Projects\hubble\node_modules\ngx-uploader\l
ib\src\ngx-uploader\module\ngx-uploader.module.js.map'
    at Error (native)
 @ ./src/app/app.module.ngfactory.ts 33:0-89
 @ ./src/app/main.ts



ionic3.  Works with "ionic build android" but doesnt work with "ionic build android --prod" 
I followed the steps above
@leo6104

**Comment by Demi-ob** [comment]
Error: ./node_modules/ngx-uploader/lib/src/ngx-uploader/classes/ngx-uploader.class.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desktop\Projects\hubble\node_modules\ngx-uploader\l
ib\src\ngx-uploader\classes\ngx-uploader.class.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 2:0-62
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/directives/ng-file-drop.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desktop\Projects\hubble\node_modules\ngx-uploader\l
ib\src\ngx-uploader\directives\ng-file-drop.directive.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 4:0-69
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/directives/ng-file-select.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desktop\Projects\hubble\node_modules\ngx-uploader\l
ib\src\ngx-uploader\directives\ng-file-select.directive.js.map'
    at Error (native)
 @ ./node_modules/ngx-uploader/lib/index.js 3:0-71
 @ ./src/pages/upload-course/upload-course.ts
 @ ./src/pages/course-tabs/course-tabs.ts
 @ ./src/pages/course-tabs/course-tabs.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-uploader/lib/src/ngx-uploader/module/ngx-uploader.module.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\DEMILADE\Desktop\Projects\hubble\node_modules\ngx-uploader\l
ib\src\ngx-uploader\module\ngx-uploader.module.js.map'
    at Error (native)
 @ ./src/app/app.module.ngfactory.ts 33:0-89
 @ ./src/app/main.ts

@leo6104   I followed  what you wrote above and got this
